# Generated by Django 5.2.11 on 2026-02-19 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'YooKassa'), ('stars', 'Telegram Stars')], max_length=10)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('canceled', 'Отменён')], default='pending', max_length=20)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_payment_id'], name='pay_provider_id')],
            },
        ),
    ]
