# Generated by Django 5.2.11 on 2026-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_provider_payment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'платёж', 'verbose_name_plural': 'платежи'},
        ),
    ]
