[pytest]
DJANGO_SETTINGS_MODULE = core.settings
asyncio_mode = auto

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --strict-markers
    --cov=.
    --cov-report=term-missing

markers =
    slow: медленные тесты (интеграционные, сеть)
    integration: интеграционные тесты (требуют БД/Redis)
