# Generated by Django 5.2.11 on 2026-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_promo_code_and_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('sbp', 'СБП'), ('stars', 'Telegram Stars')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_address_raw',
            field=models.TextField(blank=True, default=''),
        ),
    ]
